version: v1.0
name: Deploy website
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: 🏁 Deploy
    task:
      secrets:
        - name: aws-credentials
      jobs:
        - name: Copy to S3
          commands:
            - checkout
            - cache restore website-build
            - aws s3 sync "public" "s3://uncut-gatsby" --acl "public-read"
  - name: 🔍 UI tests
    task:
      jobs:
        - name: Check live website
          commands:
            - cache restore node-modules-$(checksum package-lock.json),node-modules-
            - npm run nightwatch
